// <auto-generated />
namespace Academ.io.Data.AcademContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddMM : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMM));
        
        string IMigrationMetadata.Id
        {
            get { return "201506232121398_AddM-M"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
